version: "3.3"

services:
    app-1: &app
        image: valuator-app
        build:
            context: .
        container_name: valuator_app-1
        working_dir: /app/Valuator
        command: dotnet run
        volumes:
            - ".:/app"
        ports:
            - 5001:5000
        env_file:
            - ./Valuator/.env
        networks:
            default:
                aliases:
                    - valuator-app-1
    app-2:
        <<: *app
        container_name: valuator_app-2
        ports:
            - 5002:5000
        networks:
            default:
                aliases:
                    - valuator-app-2
    redis:
        image: redis
        container_name: valuator_redis
        volumes:
            - "redis-dev-data:/data/storage"
            - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
        command:
            - "redis-server"
            - "/usr/local/etc/redis/"
        ports:
            - "6379:6379"
        
    nginx:
        image: nginx:latest
        container_name: valuator_nginx
        restart: always
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/log:/var/log/nginx
        depends_on: 
            - app-1
            - app-2
        ports:
            - 8080:8080

volumes: 
    redis-dev-data:    